# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ae2fb3e28ce286f9fb8bfdae6ab288f86de9dd684f01b536c5e3b9a6f0ee7cf89650cc9bb4da2a13690200e448ae419a8083f0859ff6e2f860b17a31422054

test:
  secret_key_base: 33626af23c8cd640e50a573d3de5e63df4c58e47f3ca6ffc4754aa2f33a3e1cf07b1cdfe02a28b83cfa48bd3caadb72d06361ca5415af54a92a4b57cbf6ffc87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
